function [sectionsOutFile, coreAverageOutFile] = NL_3_core_processing(dataFile, exportDir)

T = readtable(dataFile, 'TextType', 'string');

rho_lab = T.Density;

S_used = T.DensitySalinity;
useInterpSalinity = isnan(S_used);
S_used(useInterpSalinity) = T.InterpolatedSalinity(useInterpSalinity);

T_lab = -abs(T.LabTemperature);
T_lab(isnan(T_lab)) = -20;

T_insitu = T.InterpolatedTemperature;

[F1_pr,F2_pr] = F1F2_seaice(T_lab);
[F1_i,F2_i] = F1F2_seaice(T_insitu);

rhoi_pr = 917 - 0.1403*T_lab;
rhoi_i = 917 - 0.1403*T_insitu;

vb_pr = rho_lab .* S_used ./ F1_pr;

vg_pr = max(0, ...
    1 - rho_lab .* ...
    (F1_pr - rhoi_pr .* S_used/1000 .* F2_pr) ./ ...
    (rhoi_pr .* F1_pr));

F3_pr = rhoi_pr .* S_used/1000 ./ ...
    (F1_pr - rhoi_pr .* S_used/1000 .* F2_pr);

F3_i = rhoi_i .* S_used/1000 ./ ...
    (F1_i - rhoi_i .* S_used/1000 .* F2_i);

vb_raw = vb_pr .* F1_pr ./ F1_i / 1000;

vb_rho = vb_raw;
vb_rho(vb_rho > 0.6 | vb_rho < 0) = NaN;

A = ...
    (rhoi_i ./ rhoi_pr) .* ...
    (F3_pr ./ F3_i) .* ...
    (F1_pr ./ F1_i);

idx0 = S_used == 0;
A(idx0) = 1;

vg_connected = max(0, ...
    1 - (1 - vg_pr) .* A);

vg_disconnected = vg_pr;

% This is strict Cox and Weeks, but this is likely wrong as connected = disconnetced
% isWarming = T_insitu > T_lab;
% vg_disconnected(isWarming) = max(0, vg_pr(isWarming) + 1 - A(isWarming));

rho_si_connected = ...
    (1 - vg_connected) .* rhoi_i .* F1_i ./ ...
    (F1_i - rhoi_i .* S_used/1000 .* F2_i);

rho_si_disconnected = ...
    (1 - vg_disconnected) .* rhoi_i .* F1_i ./ ...
    (F1_i - rhoi_i .* S_used/1000 .* F2_i);

rho_si_connected(isnan(vb_rho)) = NaN;
rho_si_disconnected(isnan(vb_rho)) = NaN;

T.SalinityUsed = S_used;
T.SalinitySource = repmat("InterpolatedSalinity", height(T), 1);
T.SalinitySource(~useInterpSalinity) = "DensitySalinity";

T.LabTemperatureCorrected = T_lab;
T.InSituTemperature = T_insitu;
T.BrineVolume = vb_rho;
T.GasVolumeConnected = vg_connected;
T.GasVolumeDisconnected = vg_disconnected;
T.DensityInSituConnected = rho_si_connected;
T.DensityInSituDisconnected = rho_si_disconnected;

expandedFullTable = T;

[G_section, ~] = findgroups(expandedFullTable.DensityFile);

sectionFreeboard = NaN(height(expandedFullTable), 1);

if ismember("DensityFreeboard", expandedFullTable.Properties.VariableNames)
    sectionFreeboard = expandedFullTable.DensityFreeboard;
elseif ismember("Freeboard", expandedFullTable.Properties.VariableNames)
    sectionFreeboard = expandedFullTable.Freeboard;
end

iceDraft = expandedFullTable.IceThickness - sectionFreeboard;
depthMid = mean([expandedFullTable.MinDepth expandedFullTable.MaxDepth], 2);

tempInsituExport = round(expandedFullTable.InSituTemperature, 2);
tempLabExport = round(expandedFullTable.LabTemperatureCorrected, 2);

densityLabExport = round(expandedFullTable.Density, 2);
densityConnExport = round(expandedFullTable.DensityInSituConnected, 2);
densityDisconnExport = round(expandedFullTable.DensityInSituDisconnected, 2);

brineExport = round(expandedFullTable.BrineVolume, 3);
gasConnExport = round(expandedFullTable.GasVolumeConnected, 3);
gasDisconnExport = round(expandedFullTable.GasVolumeDisconnected, 3);

doiExport = repmat( ...
    "https://doi.org/10.21334/NPOLAR.2024.249FA73C", ...
    height(expandedFullTable), 1);

sectionData = table( ...
    expandedFullTable.Time, ...
    G_section, ...
    expandedFullTable.Lat, ...
    expandedFullTable.Lon, ...
    expandedFullTable.IceThickness, ...
    iceDraft, ...
    expandedFullTable.SnowThickness, ...
    expandedFullTable.MinDepth, ...
    expandedFullTable.MaxDepth, ...
    depthMid, ...
    tempInsituExport, ...
    tempLabExport, ...
    expandedFullTable.SalinityUsed, ...
    brineExport, ...
    round(vg_pr,3), ...
    gasConnExport, ...
    gasDisconnExport, ...
    densityLabExport, ...
    densityConnExport, ...
    densityDisconnExport, ...
    repmat("FYI", height(expandedFullTable), 1), ...
    repmat("level ice", height(expandedFullTable), 1), ...
    repmat("Nansen Legacy FYI", height(expandedFullTable), 1), ...
    doiExport, ...
    'VariableNames', { ...
        'Date/Time', ...
        'Core', ...
        'Latitude [degree_north]', ...
        'Longitude [degree_east]', ...
        'Sea ice thickness [m]', ...
        'Sea ice draft [m]', ...
        'Snow thickness [m]', ...
        'Depth top [m]', ...
        'Depth bottom [m]', ...
        'Depth mid [m]', ...
        'Temperature [degree_C]', ...
        'Temperature, technical [degree_C]', ...
        'Salinity', ...
        'Volume brine', ...
        'Volume gas, laboratory', ...
        'Volume gas, connected', ...
        'Volume gas, disconnected', ...
        'Density ice [kg m-3]', ...
        'Density ice, connected [kg m-3]', ...
        'Density ice, disconnected [kg m-3]', ...
        'Ice age', ...
        'Ice type', ...
        'Dataset', ...
        'Reference DOI'} ...
);

sectionsOutFile = fullfile(exportDir, ...
    'NL_density_parametrization_sections.xlsx');

writetable(sectionData, sectionsOutFile, ...
    'Sheet', 'Section data');

[G, ~] = findgroups(expandedFullTable.DensityFile);

sectionFreeboardCore = NaN(height(expandedFullTable), 1);

if ismember("DensityFreeboard", expandedFullTable.Properties.VariableNames)
    sectionFreeboardCore = expandedFullTable.DensityFreeboard;
elseif ismember("Freeboard", expandedFullTable.Properties.VariableNames)
    sectionFreeboardCore = expandedFullTable.Freeboard;
end

iceDraftAll = expandedFullTable.IceThickness - sectionFreeboardCore;

coreDate = splitapply(@firstValue, expandedFullTable.Time, G);
coreID = (1:max(G))';
coreLat = splitapply(@firstValue, expandedFullTable.Lat, G);
coreLon = splitapply(@firstValue, expandedFullTable.Lon, G);
coreIceThickness = splitapply(@firstValue, expandedFullTable.IceThickness, G);
coreIceDraft = splitapply(@firstValue, iceDraftAll, G);
coreTemperature = round(splitapply(@meanOmitNaN, expandedFullTable.InSituTemperature, G), 2);
coreLabTemperature = round(splitapply(@meanOmitNaN, expandedFullTable.LabTemperatureCorrected, G), 2);
coreSalinity = round(splitapply(@meanOmitNaN, expandedFullTable.SalinityUsed, G), 2);
coreBrine = round(splitapply(@meanOmitNaN, expandedFullTable.BrineVolume, G), 3);
coreGasLab = round(splitapply(@meanOmitNaN, vg_pr, G), 3);
coreGasConnected = round(splitapply(@meanOmitNaN, expandedFullTable.GasVolumeConnected, G), 3);
coreGasDisconnected = round(splitapply(@meanOmitNaN, expandedFullTable.GasVolumeDisconnected, G), 3);
coreDensity = round(splitapply(@meanOmitNaN, expandedFullTable.Density, G), 2);
coreDensityConnected = round(splitapply(@meanOmitNaN, expandedFullTable.DensityInSituConnected, G), 2);
coreDensityDisconnected = round(splitapply(@meanOmitNaN, expandedFullTable.DensityInSituDisconnected, G), 2);
coreSnowThickness = splitapply(@firstValue, expandedFullTable.SnowThickness, G);

coreAverageExport = table( ...
    coreDate, ...
    coreID, ...
    coreLat, ...
    coreLon, ...
    coreIceThickness, ...
    coreIceDraft, ...
    coreTemperature, ...
    coreLabTemperature, ...
    coreSalinity, ...
    coreBrine, ...
    coreGasLab, ...
    coreGasConnected, ...
    coreGasDisconnected, ...
    coreDensity, ...
    coreDensityConnected, ...
    coreDensityDisconnected, ...
    coreSnowThickness, ...
    repmat("FYI", max(G), 1), ...
    repmat("level ice", max(G), 1), ...
    repmat("Nansen Legacy FYI", max(G), 1), ...
    repmat("https://doi.org/10.21334/NPOLAR.2024.249FA73C", max(G), 1), ...
    'VariableNames', { ...
        'Date/Time', ...
        'Core', ...
        'Latitude [degree_north]', ...
        'Longitude [degree_east]', ...
        'Sea ice thickness [m]', ...
        'Sea ice draft [m]', ...
        'Temperature [degree_C]', ...
        'Temperature, technical [degree_C]', ...
        'Salinity', ...
        'Volume brine', ...
        'Volume gas, laboratory', ...
        'Volume gas, connected', ...
        'Volume gas, disconnected', ...
        'Density ice [kg m-3]', ...
        'Density ice, connected [kg m-3]', ...
        'Density ice, disconnected [kg m-3]', ...
        'Snow thickness [m]', ...
        'Ice age', ...
        'Ice type', ...
        'Dataset', ...
        'Reference DOI'} ...
);

coreAverageExport = sortrows(coreAverageExport, 'Date/Time');

coreAverageOutFile = fullfile(exportDir, ...
    'NL_density_parametrization_core_average.xlsx');

writetable(coreAverageExport, coreAverageOutFile, ...
    'Sheet', 'Core summary');

fprintf('\nSaved:\n');
fprintf('%s\n', sectionsOutFile);
fprintf('%s\n', coreAverageOutFile);

%% Helpers

function y = meanOmitNaN(x)

y = mean(x, 'omitnan');

end

function y = firstValue(x)

y = x(1);

end

function [F1,F2] = F1F2_seaice(T)

F1 = -4.732 - 22.45*T - 0.6397*T.^2 - 0.01074*T.^3;
F2 = 8.903e-2 - 1.763e-2*T - 5.33e-4*T.^2 - 8.801e-6*T.^3;

idxWarm = T > -2;

F1(idxWarm) = -4.1221e-2 - 18.407*T(idxWarm) + ...
    0.58402*T(idxWarm).^2 + 0.21454*T(idxWarm).^3;

F2(idxWarm) = 9.0312e-2 - 0.016111*T(idxWarm) + ...
    1.2291e-4*T(idxWarm).^2 + 1.3603e-4*T(idxWarm).^3;

idxCold = T < -22.9;

F1(idxCold) = 9899 + 1309*T(idxCold) + ...
    55.27*T(idxCold).^2 + 0.7160*T(idxCold).^3;

F2(idxCold) = 8.547 + 1.089*T(idxCold) + ...
    0.04518*T(idxCold).^2 + 5.819e-4*T(idxCold).^3;

end

end